; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Tue Feb 27 2018 21:33:13 GMT+0100 (CET)
M98 P/macros/ZConfig

M98 P/macros/InicialCalibracion

M561 ; clear any bed transform
G28

G29

M98 P/macros/FinalCalibracion