; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool on Fri Jun 09 2017 20:42:49 GMT+0200 (CEST)

; Lift Z relatively to current position
G91
G1 Z5 F6000

; Back to absolute positioning
G90

; Go to first bed probe point and home the Z axis
G1 X0 Y0 F2000
G4 S1
G30

; Uncomment the following lines to lift Z after probing
;G91
G1 Z5 F100
;G90
