; G-Code generated by Simplify3D(R) Version 4.0.0 at 21:38 10/Nov/2017
M98 P/macros/InicialCalibracion

G30 P0 X150 Y0 Z-99999 F2000 
G30 P1 X150 Y0 Z-99999 F2000 
G30 P2 X150 Y0 Z-99999 F2000 S-1

M98 P/macros/FinalCalibracion