; G-Code generated by Simplify3D(R) Version 4.0.0 at 21:38 10/Nov/2017
M98 P/macros/InicialCalibracion

;prob testing single point. 
G30 P0 X0 Y0 Z-99999 
G30 P1 X0 Y0 Z-99999 
G30 P2 X0 Y0 Z-99999 S-1
;G30 P3 X0 Y0 Z-99999 
;G30 P4 X0 Y0 Z-99999
;G30 P5 X0 Y0 Z-99999 
;G30 P6 X0 Y0 Z-99999 
;G30 P7 X0 Y0 Z-99999 
;G30 P8 X0 Y0 Z-99999 
;G30 P9 X0 Y0 Z-99999
;G30 P10 X0 Y0 Z-99999 S-1

M98 P/macros/FinalCalibracion